site_name: Fundamentos en Ciencias de la Computación
theme:
  name: material
  logo: images/logo.png
extra_css:
  - stylesheets/extra.css
nav:
  - Inicio: index.md
  - Unidades:
    - 1. Ser Ing. en el s.XXI: unidad/1/readme.md
    - 2. Orígenes y fundamentos: unidad/2/readme.md
    - 3. Sistemas y herramientas: unidad/3/readme.md
    - 4. Estructuras y procesos: unidad/4/readme.md
    - 5. Alfabetización en IA: unidad/5/readme.md
    - 6. Soluciones y trayectorias: unidad/6/readme.md
  - Acerca de: acerca_de.md

